#!/bin/bash
set -eu
info(){
    echo "$@"
    notify-send "$@"
}

error(){
    echo "ERROR: $@"
    notify-send "$@"
}

[[ "$1" == "--force" ]] && force=true || force=false

working_tree_clean(){
    git status $1 | grep "nothing to commit, working tree clean" > /dev/null
}

processed=false
for zipfile in "$@"; do
    processed=true
    outdir=$(mktemp -d "/tmp/${zipfile}-XXX")
    unzip $zipfile -d "$outdir" > /dev/null && mv "$zipfile"{,.extracted}
    rsync -a --delete --exclude ".git"  "$outdir"/ "${zipfile%.*}"/
    rm -r "$outdir"
    info "aeCAD Extract" "\"$zipfile\" is extracted."
done

$processed || echo "No project supplied."
